apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitops-applications
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitops-application
  template:
    metadata:
      labels:
        app: gitops-application
    spec:
      containers:
      - image: mapspiral/gitops-application:v1
        name: gitops-application
        ports:
        - containerPort: 8080
